### ISSUE TITLE
docker gpu driver missing

### ISSUE THREAD

**Issue by rotten** [pixray/pixray#11]
I tried running this on Ubuntu 20.04.

After about an hour of processing and downloading, I got this:
```
Running 'python pixray.py --drawer=pixel --prompt=sunrise --output /tmp/giant1.png' in Docker with the current directory mounted as a volume...
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

It isn't obvious to me how to pass `--gpus all` to the docker image, so I tried updating the `cog.yaml` to have `gpu: false`.  Unfortunately that throws a build failure too:

```#16 16.98 CMake Error at /usr/local/lib/python3.8/site-packages/cmake/data/share/cmake-3.21/Modules/FindCUDA.cmake:859 (message):
#16 16.98   Specify CUDA_TOOLKIT_ROOT_DIR
#16 16.98 Call Stack (most recent call first):
#16 16.98   CMakeLists.txt:19 (find_package)
#16 16.98
#16 16.98
#16 16.98 -- Configuring incomplete, errors occurred!
#16 16.98 See also "/diffvg/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
#16 16.98 Traceback (most recent call last):
#16 16.98   File "setup.py", line 91, in <module>
#16 16.98     setup(name = 'diffvg',
#16 16.98   File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
#16 16.98     return distutils.core.setup(**attrs)
#16 16.98   File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
#16 16.98     dist.run_commands()
#16 16.98   File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
#16 16.98     self.run_command(cmd)
#16 16.98   File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
#16 16.99     cmd_obj.run()
#16 16.99   File "/usr/local/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
#16 16.99     self.do_egg_install()
#16 16.99   File "/usr/local/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
#16 16.99     self.run_command('bdist_egg')
#16 16.99   File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
#16 16.99     self.distribution.run_command(command)
#16 16.99   File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
#16 16.99     cmd_obj.run()
#16 16.99   File "/usr/local/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
#16 16.99     cmd = self.call_command('install_lib', warn_dir=0)
#16 16.99   File "/usr/local/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
#16 16.99     self.run_command(cmdname)
#16 16.99   File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
#16 16.99     self.distribution.run_command(command)
#16 16.99   File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
#16 16.99     cmd_obj.run()
#16 16.99   File "/usr/local/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
#16 16.99     self.build()
#16 16.99   File "/usr/local/lib/python3.8/distutils/command/install_lib.py", line 107, in build
#16 16.99     self.run_command('build_ext')
#16 16.99   File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
#16 16.99     self.distribution.run_command(command)
#16 16.99   File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
#16 16.99     cmd_obj.run()
#16 16.99   File "setup.py", line 31, in run
#16 16.99     super().run()
#16 16.99   File "/usr/local/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
#16 16.99     _build_ext.run(self)
#16 16.99   File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 340, in run
#16 16.99     self.build_extensions()
#16 16.99   File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
#16 16.99     self._build_extensions_serial()
#16 16.99   File "/usr/local/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
#16 16.99     self.build_extension(ext)
#16 16.99   File "setup.py", line 64, in build_extension
#16 16.99     subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
#16 16.99   File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
#16 16.99     raise CalledProcessError(retcode, cmd)
#16 16.99 subprocess.CalledProcessError: Command '['cmake', '/diffvg', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/diffvg/build/lib.linux-x86_64-3.8', '-DPYTHON_INCLUDE_PATH=/usr/local/include/python3.8', '-DCMAKE_BUILD_TYPE=Release', '-DDIFFVG_CUDA=1']' returned non-zero exit status 1.
------
executor failed running [/bin/sh -c git clone https://github.com/pixray/diffvg && cd diffvg && git submodule update --init --recursive && CMAKE_PREFIX_PATH=$(pyenv prefix) DIFFVG_CUDA=1 python setup.py install]: exit code: 1
ⅹ Failed to build Docker image: exit status 1
```

Do you have any suggestions for how to get the gpu drivers into the cog container, or lacking that, how to disable the gpu dependency?

**Comment by palexpereira** [comment]
I had the same problem. Make sure you have cuda installed.

**Comment by rotten** [comment]
I tried:
```
sudo apt install nvidia-cuda-toolkit
sudo apt install nvidia-docker2
```
The former picked up a bunch of supporting CUDA libraries and utilities, the latter worked after adding a repository.

Sadly, I get this now:
```
Running 'python pixray.py --drawer=pixel --prompt=sunrise --output /tmp/sunrise.png' in Docker with the current directory mounted as a volume...
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
ⅹ exit status 125
```

Perhaps I don't have the exact hardware combination this tool needs to work.  Or maybe I'm still missing some other detail that isn't obvious.  It was worth a shot.

**Comment by dribnet** [comment]
Sorry - we can't fully debug docker issues. Note that docker and cog are optional - you can also use the `requirements.txt` file directly on ubuntu.
