### ISSUE TITLE
needs more than 16 gigs of ram?

### ISSUE THREAD

**Issue by matthiaskrgr** [pixray/pixray#2]
Hi, was really amazed by what the website thingy can do https://pixray.gob.io/text2image/ so I tried to run pixray locally.

In the docs I read that 16 gigs of ram should be enough, but when I try to run a primitive program like this:
````python
import pixray
pixray.reset_settings()
pixray.add_settings(prompts="hellfire burning")
settings = pixray.apply_settings()
pixray.do_init(settings)
pixray.do_run(settings)
````

it takes a bit and then I can see my system memory being eaten up at around half a gigabyte per second until my laptop freezes or I terminate the program if I am quick enough

````
--> Not running with pydiffvg drawer support  No module named 'pydiffvg'
Using seed: 10631471561177097992
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips/vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.
Restored from models/vqgan_imagenet_f16_16384.ckpt
Using device: cpu
Optimising using: Adam
Using text prompts: ['hellfire burning']
0it [00:00, ?it/s]/home/matthias/.local/lib/python3.9/site-packages/torch/nn/functional.py:3631: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
/home/matthias/.local/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
0it [00:18, ?it/s]
^CTraceback (most recent call last):
  File "/home/matthias/vcs/github/pixray/paint.py", line 6, in <module>
    pixray.do_run(settings)
  File "/home/matthias/vcs/github/pixray/pixray.py", line 1472, in do_run
    pass
````

is there anything I can do to reduce the need for memory?

Hardware: I have a i5-7200U with 16 gigs of ram and no dedicated gpu in case that matters.

**Comment by dribnet** [comment]
Try quality=draft

**Comment by dribnet** [comment]
let me know if you need more tips here. the other thing you can do is try reducing num_cuts and potentially bumping up batches from 1 to 2.
