### ISSUE TITLE
No module named 'tokenizer'

### ISSUE THREAD

**Issue by explodingkittns** [pixray/pixray#20]
After updating to the latest version of Pixray, I am now getting the following error when trying to run it locally:

```
$ cog run python pixray.py --output cat.png --quality=better --num_cuts=7 --prompts="a really cool cat" --aspect=portrait              Building Docker image from environment in cog.yaml...
[+] Building 407.1s (19/19) FINISHED                                                                                                                                       
=> [internal] load build definition from Dockerfile                                                                                                                  0.0s
=> => transferring dockerfile: 1.62kB                                                                                                                                0.0s
=> [internal] load .dockerignore                                                                                                                                     0.0s
=> => transferring context: 2B                                                                                                                                       0.0s
 => resolve image config for docker.io/docker/dockerfile:1.2                                                                                                          0.6s
 => CACHED docker-image://docker.io/docker/dockerfile:1.2@sha256:e2a8561e419ab1ba6b2fe6cbdf49fd92b95912df1cf7d313c3e2230a333fdbcc                                     0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04                                                                                  0.9s
 => [stage-0  1/11] FROM docker.io/nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04@sha256:61f4c02abaaa2470ab2af28f0bf4b4605c8d662e23c9958729b84d6b43c4ddb6                 78.5s
 => => resolve docker.io/nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04@sha256:61f4c02abaaa2470ab2af28f0bf4b4605c8d662e23c9958729b84d6b43c4ddb6                            0.0s
 => => sha256:61f4c02abaaa2470ab2af28f0bf4b4605c8d662e23c9958729b84d6b43c4ddb6 745B / 745B                                                                            0.0s
 => => sha256:019d4a9aa36133b8206cae70dcf0e427ecc164a5465cd8acf41d601ad160331c 14.93kB / 14.93kB                                                                      0.0s
 => => sha256:284055322776031bac33723839acb0db2d063a525ba4fa1fd268a831c7553b26 26.71MB / 26.71MB                                                                      1.4s
 => => sha256:3d1aefa978b106e8cbe50743bba8c4ddadacf13fe3165dd67a35e4d904f3aabe 2.42kB / 2.42kB                                                                        0.0s
 => => sha256:add8cbaa9fce426638c1b835d63f57b4063c53378d4de1c5edf3b7c2e8991620 7.22MB / 7.22MB                                                                        0.4s
 => => sha256:a884b5401cbf96a53e5ce6c9097fad5dd5628c3f3c266ce61489940303881765 9.55MB / 9.55MB                                                                        0.7s
 => => sha256:dafa3e5bf39d2a52a43fcf166a9e57031ff545ca6e15f3dc5776bac9ebc069ec 184B / 184B                                                                            0.5s
 => => sha256:be7367c7df1275ad2c320e86151c8afe92447abe7c2f387b1d565e4008e8a584 6.43kB / 6.43kB                                                                        0.7s
 => => sha256:9437169e9a8d5ed24a5b0adfefee73a831e3d4d8ed1fb665e5c55031b0983cba 759.32MB / 759.32MB                                                                   27.7s
 => => sha256:fe201c3ac6fffd8752986765b5573ffdd0707d5eef41bd5bb4b1c23496403776 62.76kB / 62.76kB                                                                      0.9s
 => => sha256:17120ad615e73e9d41a1a5ce271ee2678d95cf9fc96d58f5d20b8ab9b495c13d 882.08MB / 882.08MB                                                                   33.2s
 => => extracting sha256:284055322776031bac33723839acb0db2d063a525ba4fa1fd268a831c7553b26                                                                             0.7s
 => => sha256:f9fe2e758f6568f41bf06f72570b82113c7b4a484cfe88b6a324086eee6775fa 87.57kB / 87.57kB                                                                      1.5s
 => => sha256:28cb2614ece8df2263525c2ca2a69f1878ceb2f58895fc0ad94403cbe0147de5 1.02GB / 1.02GB                                                                       35.3s
 => => extracting sha256:add8cbaa9fce426638c1b835d63f57b4063c53378d4de1c5edf3b7c2e8991620                                                                             0.2s
 => => extracting sha256:a884b5401cbf96a53e5ce6c9097fad5dd5628c3f3c266ce61489940303881765                                                                             0.2s
 => => extracting sha256:dafa3e5bf39d2a52a43fcf166a9e57031ff545ca6e15f3dc5776bac9ebc069ec                                                                             0.0s
 => => extracting sha256:be7367c7df1275ad2c320e86151c8afe92447abe7c2f387b1d565e4008e8a584                                                                             0.0s
 => => extracting sha256:9437169e9a8d5ed24a5b0adfefee73a831e3d4d8ed1fb665e5c55031b0983cba                                                                            13.5s
 => => extracting sha256:fe201c3ac6fffd8752986765b5573ffdd0707d5eef41bd5bb4b1c23496403776                                                                             0.0s
 => => extracting sha256:17120ad615e73e9d41a1a5ce271ee2678d95cf9fc96d58f5d20b8ab9b495c13d                                                                            16.7s
 => => extracting sha256:f9fe2e758f6568f41bf06f72570b82113c7b4a484cfe88b6a324086eee6775fa                                                                             0.0s
 => => extracting sha256:28cb2614ece8df2263525c2ca2a69f1878ceb2f58895fc0ad94403cbe0147de5                                                                            19.9s
 => [internal] load build context                                                                                                                                     0.0s
 => => transferring context: 22.09kB                                                                                                                                  0.0s
 => [stage-0  2/11] RUN --mount=type=cache,target=/var/cache/apt apt-get update -qq && apt-get install -qqy --no-install-recommends  make  build-essential  libssl-  26.1s
=> [stage-0  3/11] RUN curl https://pyenv.run | bash &&  git clone https://github.com/momo-lab/pyenv-install-latest.git "$(pyenv root)"/plugins/pyenv-install-late  59.1s
=> [stage-0  4/11] COPY .cog/tmp/build3319676509/cog-0.0.1.dev-py3-none-any.whl /tmp/cog-0.0.1.dev-py3-none-any.whl                                                  0.1s
=> [stage-0  5/11] RUN --mount=type=cache,target=/root/.cache/pip pip install /tmp/cog-0.0.1.dev-py3-none-any.whl                                                    2.9s
=> [stage-0  6/11] COPY requirements.txt /tmp/requirements.txt                                                                                                       0.0s
=> [stage-0  7/11] RUN --mount=type=cache,target=/root/.cache/pip pip install -r /tmp/requirements.txt && rm /tmp/requirements.txt                                 182.5s
=> [stage-0  8/11] RUN apt-get update                                                                                                                                4.1s
=> [stage-0  9/11] RUN apt install -y libgl1-mesa-glx                                                                                                                7.7s
=> [stage-0 10/11] RUN git clone https://github.com/pixray/diffvg && cd diffvg && git submodule update --init --recursive && CMAKE_PREFIX_PATH=$(pyenv prefix) DIF  33.2s
=> [stage-0 11/11] WORKDIR /src                                                                                                                                      0.0s
=> exporting to image                                                                                                                                                0.0s
=> => exporting layers                                                                                                                                               0.0s
=> => writing image sha256:bf40eaccf6ed12adaeb7c3180330adaa11a194d177f78fb0a49bffc10a3765b9                                                                          0.0s
=> => naming to docker.io/library/cog-pixray-base                                                                                                                    0.0s
=> exporting cache                                                                                                                                                   0.0s
=> => preparing build cache for export                                                                                                                               0.0s

Running 'python pixray.py --output cat.png --quality=better --num_cuts=7 --prompts=a really cool cat --aspect=portrait' in Docker with the current directory mounted as a volume...
Traceback (most recent call last):
  File "pixray.py", line 32, in <module>
    from slip import get_clip_perceptor
  File "/src/slip.py", line 80, in <module>
    from tokenizer import SimpleTokenizer
ModuleNotFoundError: No module named 'tokenizer'
ⅹ exit status 1
```

I have ensured that my Docker cache is clean with `docker system prune` and that all images have been removed, so we're working with a clean slate. I have also ensured Cog and Docker are up to date. Finally, I cloned the repo again to ensure it is completely clean and in sync with remote, but I am still getting this error.

I am running this on my Ubuntu 20.04.3 machine, with Docker 20.10.12 and Cog 0.0.20. This used to work just fine, but since pulling the repo today, it is no longer working.

**Comment by dribnet** [comment]
New with the latest version are submodules - so you will need to `clone --recursive` (or otherwise sync up the `SLIP` and `v-diffusion-pytorch` subdirectories). Can you confirm this step as well?

**Comment by explodingkittns** [comment]
Looks like that was it! Thank you!

**Comment by dribnet** [comment]
Great and sorry about that - I'll try to make it more clear in the README, etc. as this is a new process.
