### ISSUE TITLE
KeyError: pixel

### ISSUE THREAD

**Issue by thelabcat** [pixray/pixray#46]
```
PS C:\Users\myself\Downloads\pixray> python pixray.py --drawer=pixel --prompt=cheese --outdir olc01
--> Not running with pydiffvg drawer support  No module named 'pydiffvg'
Traceback (most recent call last):
  File "pixray.py", line 2063, in <module>
    main()
  File "pixray.py", line 2055, in main
    settings = apply_settings()
  File "pixray.py", line 1998, in apply_settings
    class_table[settings_core.drawer].add_settings(vq_parser)
KeyError: 'pixel'
```
What did I do wrong?

**Comment by samedii** [comment]
Looks like pydiffvg isn't installed. Pixel drawer is only supported if it's installed.

```
--> Not running with pydiffvg drawer support  No module named 'pydiffvg'
```

**Comment by thelabcat** [comment]
> pydiffvg

How to install? It's not on PIP.

**Comment by samedii** [comment]
Look here https://github.com/pixray/pixray/blob/master/cog.yaml. I normally run things using cog (docker) so it fixes this stuff for me.

I agree this could be documented and I'd recommend joining the discord channel. The same question has probably been asked there before.

**Comment by dribnet** [comment]
On ubuntu the install for diffvg is
```bash
git clone https://github.com/pixray/diffvg && cd diffvg && git submodule update --init --recursive && CMAKE_PREFIX_PATH=$(pyenv prefix) DIFFVG_CUDA=1 python setup.py install
```

**Comment by thelabcat** [comment]
> On ubuntu the install for diffvg is
> 
> ```bash
> 
> git clone https://github.com/pixray/diffvg && cd diffvg && git submodule update --init --recursive && CMAKE_PREFIX_PATH=$(pyenv prefix) DIFFVG_CUDA=1 python setup.py install
> 
> ```

I am on windows 11. However, I somewhat gave up on The project when I encountered a Vram error. I only have 8GB, and apparently that wasn't enough.

**Comment by entangledloops** [comment]
@dribnet Ran that command on ubuntu, but then you hit:

```
-- Using pybind11: (version "2.6.0" dev)
-- Build with CUDA support
CMake Error at /home/snd/bin/miniconda3/envs/pixray/lib/python3.8/site-packages/cmake/data/share/cmake-3.21/Modules/FindCUDA.cmake:859 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:19 (find_package)
```
I'm guessing you need the CUDA toolkit as well. I ended up here b/c I followed the instructions (used recursive clone + conda + python 3.8 + requirements.txt), but still hit this error on first run of `pixray.py`.

**Comment by realgdman** [comment]
I faced this problem on Colab, what I've discovered after several hours of digging is that Python was building Tensorflow with c++11 while it should be c++14. 
exact error was [error: use of ‘auto’ in lambda parameter declaration only available with ‘-std=c++14’ or ‘-std=gnu++14’]
So I've updated c++ standard in diffvg/pydiffvg_tensorflow/custom_ops/CMakeLists.txt

Of course that was not enough, because now it looks I need to downgrade Kornia.

**Comment by danishaman202** [comment]
Please can anyone refer me a remedy for this?
I am on windows 10 and encountering same error, Please can anyone suggest me what to do?

**Comment by samedii** [comment]
Are you sure you really want to use the pixeldrawer? There is a "fast pixeldrawer" too that only does rectangles but I suspect maybe you don't want to draw hexagons etc?

**Comment by thelabcat** [comment]
No, I just wanted it to draw something.

**Comment by thelabcat** [comment]
> Are you sure you really want to use the pixeldrawer? There is a "fast pixeldrawer" too that only does rectangles but I suspect maybe you don't want to draw hexagons etc?

I would probably have been happy with any functionality.

**Comment by ValerianRey** [comment]
> On ubuntu the install for diffvg is
> 
> ```shell
> git clone https://github.com/pixray/diffvg && cd diffvg && git submodule update --init --recursive && CMAKE_PREFIX_PATH=$(pyenv prefix) DIFFVG_CUDA=1 python setup.py install
> ```

I'm on Ubuntu 20.04, using a 3.8.13 python managed by pyenv + virtualenv.
I had another error running this during the CMAKE because my gcc version was too high (9.4.0). I followed https://stackoverflow.com/questions/65605972/cmake-unsupported-gnu-version-gcc-versions-later-than-8-are-not-supported (note that it downgrades gcc and g++ to version 7.0 so use with caution). I also had to install ffmpeg manually: `sudo apt install ffmpeg`

Now I can use drawer='pixel' without any problem, and the image generation works.
