### ISSUE TITLE
FileNotFoundError, seems to be that the model cannot download

### ISSUE THREAD

**Issue by thelabcat** [pixray/pixray#47]
```
pixray.run("an extremely hairy panda bear", "vdiff", custom_loss="aesthetic", outdir="outputs/hairout")
Using seed: 169732912695400
Downloading models/yfcc_2.pth from https://v-diffusion.s3.us-west-2.amazonaws.com/yfcc_2.pth, please wait
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zargu\Downloads\pixray\pixray.py", line 2051, in run
    do_init(settings)
  File "C:\Users\zargu\Downloads\pixray\pixray.py", line 606, in do_init
    drawer.load_model(args, device)
  File "C:\Users\zargu\Downloads\pixray\vdiff.py", line 83, in load_model
    wget_file(model_urls[self.vdiff_model],checkpoint)
  File "C:\Users\zargu\Downloads\pixray\util.py", line 243, in wget_file
    output = subprocess.check_output(['wget', '-O', out, url])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by samedii** [comment]
Did your download fail? Does the file `models/yfcc_2.pth` exist?

**Comment by dribnet** [comment]
Downloads currently depend on wget, which might not be available on windows. If you put the files in place manually then wget will not be triggered.

**Comment by dribnet** [comment]
As a workaround you can also just download the file manually as wget only kicks in when the file is missing.

**Comment by thelabcat** [comment]
> As a workaround you can also just download the file manually as wget only kicks in when the file is missing.

It's been a while since I worked on this project. I think I tried that, and it did work, but I ran into a different issue. Thanks.
