### ISSUE TITLE
No module named 'tokenizer'

### ISSUE THREAD

**Issue by mayankjain89** [pixray/pixray#58]
python pixray.py --drawer=pixel --prompt=sunrise --outdir sunrise01
Traceback (most recent call last):
  File "/home/mayank/Downloads/pixray-master/pixray.py", line 35, in <module>
    from slip import get_clip_perceptor
  File "/home/mayank/Downloads/pixray-master/slip.py", line 81, in <module>
    from tokenizer import SimpleTokenizer
ModuleNotFoundError: No module named 'tokenizer'

**Comment by ryudrigo** [comment]
As stated in the README, you have to clone with ```git clone --recursive```

**Comment by ccargill-ewx** [comment]
Having same issue, I did clone recursive, any other ideas? Many thanks.

**Comment by Fabian-B-explore** [comment]
I have ran into that exact same issue and managed to fixed it by running the following code below. Please note that I ran it in a google colab notebook because jupyter notebooks is extremely slow. If you however have 16GB RAM and a good GPU then feel free to run it in jupyter locally. Also please install each module in this order.

!pip install torch==1.9.0+cu111 torchtext==0.10.0 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch/ -f https://download.pytorch.org/whl/torchvision/

`!git clone https://github.com/openai/CLIP
!git clone https://github.com/CompVis/taming-transformers.git
!rm -Rf pixray
!git clone https://github.com/dribnet/pixray
!pip install ftfy regex tqdm omegaconf pytorch-lightning
!pip install kornia==0.6.1
!pip install imageio-ffmpeg   
!pip install einops
!pip install torch-optimizer
!pip install easydict
!pip install braceexpand
!pip install git+https://github.com/pvigier/perlin-numpy
!mkdir steps
!mkdir models`

As to why the errors are occurring, my guess is that there seems to inadvertently be some issue with taming transformers? In any case this should solve it

**Comment by Fabian-B-explore** [comment]
I had the exact same error. I solved it by running the following code immediately after installing all dependencies. Once you run this code please restart the kernel/program for the changes to take effect. you should not be getting the "no module named tokenizer error" anymore:

`import sys`

`sys.path.append("pixray")`
