### ISSUE TITLE
MissingSchema: Invalid URL 'stringtempfile.png': No scheme supplied. Perhaps you meant http://stringtempfile.png?

### ISSUE THREAD

**Issue by VladoPortos** [pixray/pixray#67]
I have a strange issue whereupon finishing I get this below. I'm running it inside COG docker image, so I'm not sure if it's COGs issue or pixray.

```
.
.
.
iter: 250, finished (-47=>1.551)
0it [00:00, ?it/s]
INFO:     10.0.0.139:57258 - "POST /predictions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/site-packages/cog/server/http.py", line 91, in predict
    encoded_response = encode_json(
  File "/usr/local/lib/python3.8/site-packages/cog/json.py", line 27, in encode_json
    return encode_json(obj.dict(exclude_unset=True), upload_file)
  File "/usr/local/lib/python3.8/site-packages/cog/json.py", line 29, in encode_json
    return {key: encode_json(value, upload_file) for key, value in obj.items()}
  File "/usr/local/lib/python3.8/site-packages/cog/json.py", line 29, in <dictcomp>
    return {key: encode_json(value, upload_file) for key, value in obj.items()}
  File "/usr/local/lib/python3.8/site-packages/cog/json.py", line 31, in encode_json
    return [encode_json(value, upload_file) for value in obj]
  File "/usr/local/lib/python3.8/site-packages/cog/json.py", line 31, in <listcomp>
    return [encode_json(value, upload_file) for value in obj]
  File "/usr/local/lib/python3.8/site-packages/cog/json.py", line 36, in encode_json
    return upload_file(f)
  File "/usr/local/lib/python3.8/site-packages/cog/server/http.py", line 92, in <lambda>
    response, upload_file=lambda fh: upload_file(fh, output_file_prefix)
  File "/usr/local/lib/python3.8/site-packages/cog/files.py", line 15, in upload_file
    resp = requests.put(url, files={"file": fh})
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 132, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'stringtempfile.png': No scheme supplied. Perhaps you meant http://stringtempfile.png?
```

**Comment by dribnet** [comment]
I think this is a weird ffmpeg issue. It tries to make a movie of all the frames at the end, but you can disable this via `save_intermediates=False`

**Comment by VladoPortos** [comment]
@dribnet thanks, movie would be nice :) but final image as well.. Not sure if I called it ok… I just started to experiment with COG and ML a few days ago, so I'm stumbling around like a toddler.

I called it from UI made by COG /docs, so maybe that was worng... also I edited out GPU usage as my 4G GPU just streight out died (Out of RAM) - looking into 12GB RTX 2060 now :)

```
{
  "input": {
    "prompts": "Pyramid",
    "drawer": "vqgan",
    "settings": "\n"
  },
  "output_file_prefix": "string"
}
```

**Comment by VladoPortos** [comment]
I finally got output :) the issue was here:

```
{
  "input": {
    "prompts": "Pyramid",
    "drawer": "vqgan",
    "settings": "\n"
  },
  "output_file_prefix": "string" <---HERE
}
```

Changed it to:

```
{
  "input": {
    "prompts": "Pyramid",
    "drawer": "vqgan",
    "settings": "iterations: 30"
  }

```
Now it returns base64 encoded files.

Couple interesting facts:
running **quality: best** easily use more than 12GB of GPU ram ( not sure how much, since mine is going to 12G only :D )
running **quality: better** consume also more than 12GB of GPU ram
running **quality: normal** Consume around 8217MiB

Is there a way to handle this ? I don't think I can get Nvidia Tesla with 24G+ ram :D ( not sure even how much ram the model uses all together. )
