### ISSUE TITLE
No module named 'pydiffvg' and FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by MrKaplanP** [pixray/pixray#76]
I try to run it and I get two things...

`--> Not running with pydiffvg drawer support  No module named 'pydiffvg'
Running with 30x1 = 30 cuts
Using seed: 297200249813900
Downloading models/yfcc_2.pth from https://the-eye.eu/public/AI/models/v-diffusion/yfcc_2.pth, please wait
Traceback (most recent call last):
  File "pixray.py", line 2135, in <module>
    main()
  File "pixray.py", line 2129, in main
    do_init(settings)
  File "pixray.py", line 613, in do_init
    drawer.load_model(args, device)
  File "C:\Users\MrKaplan\pixray\vdiff.py", line 87, in load_model
    wget_file(model_urls[self.vdiff_model],checkpoint)
  File "C:\Users\MrKaplan\pixray\util.py", line 266, in wget_file
    output = subprocess.check_output(['wget', '-O', out, url])
  File "C:\Users\MrKaplan\anaconda3\envs\python38\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\MrKaplan\anaconda3\envs\python38\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\MrKaplan\anaconda3\envs\python38\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\MrKaplan\anaconda3\envs\python38\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

Any clues as why i get this error while the file is in the specified folder and the path is correct?
Also why it cant find the module? i tried to find on internet and cant find it either to download it either as wheel or using pip

**Comment by kengkreingkrai** [comment]
like me.

`--> Not running with pydiffvg drawer support  No module named 'pydiffvg'
Traceback (most recent call last):
  File "...\pixray\pixray.py", line 2135, in <module>
    main()
  File "...\pixray\pixray.py", line 2127, in main
    settings = apply_settings()
  File "...\pixray.py", line 2070, in apply_settings
    class_table[settings_core.drawer].add_settings(vq_parser)
KeyError: 'pixel'`

**Comment by MrKaplanP** [comment]
yea if i try --drawer=pixel i get the same KeyError as you... any luck so far?

Edit: After checking the code i manage to get it running by changing:

```
This:
if settings.vqgan_config is None:
            config_path = f'models/vqgan_{self.vqgan_model}.yaml'
        else:
            config_path = settings.config_path
            
        if settings.vqgan_checkpoint is None:
            checkpoint_path = f'models/vqgan_{self.vqgan_model}.ckpt'
        else:
            checkpoint_path = settings.checkpoint_path
```

To this:
```
if settings.vqgan_config is None:
            config_path = f'models/model.yaml'
        else:
            config_path = settings.config_path
            
        if settings.vqgan_checkpoint is None:
            checkpoint_path = f'models/last.ckpt'
        else:
            checkpoint_path = settings.checkpoint_path
```

In file vqgan.py after downloading them manually and move them to folder named "models"
