### ISSUE TITLE
Slip - Clip Interceptor - Timm Models (clean install)

### ISSUE THREAD

**Issue by Axoridex** [pixray/pixray#91]
After trying multiple different install approaches, including a fresh ubuntu install, WSL and embedded python on windows; using python 3.8 and a no error installation (after recursive cloning) from the install -r requirements.txt and the install basicrs, I keep getting the following error when running pixray.py (with different parameters) and I do not know how to fix it:

```
Traceback (most recent call last):
  File "pixray.py", line 35, in <module>
    from slip import get_clip_perceptor
  File "C:\Users\julia\pixray\slip.py", line 80, in <module>
    import models
  File "C:\Users\julia\pixray\SLIP\models.py", line 257, in <module>
    @timm.models.registry.register_model
AttributeError: module 'timm.models' has no attribute 'registry'
```

Do I need to manually upgrade or downgrade slip (and how)? Or is there something else wrong that I can fix myself?

**Comment by tsredanovic** [comment]
Im geting the same error, did you find a way to fix it?

**Comment by thelazurite-cell** [comment]
Issue is timm has been updated since like you thought,
either update the requirements.txt file or add the following to your pixray_install section of your notebook:
`!pip install timm==0.6.5`

![image](https://github.com/pixray/pixray/assets/75317253/12bfdee9-a449-4170-ba94-e9e4bd002cb4)


As I was messing around with it a little bit, I may have made some unnecessary changes here, but if the above suggested does not work, here's my complete changes

```python
#@title pixray_install
#@markdown Run this once, then "Restart and Run all"
%%capture
pixray_version = "next planned release" #@param ["latest release", "next planned release"]
branch = "release"
if pixray_version == "next planned release":
  branch = "master"
!rm -Rf pixray
!touch ./reqs.txt
!pip install braceexpand 
!pip install basicsr
!pip install pydiffvg 
!pip install pillow 
!pip install pytesseract
!pip install omegaconf colorthief
!pip install torch_optimizer transformers==4.26.1
!pip3 install git+https://github.com/pvigier/perlin-numpy
!pip3 install  git+https://github.com/openai/CLIP
!pip3 install git+https://github.com/bfirsh/taming-transformers.git@7a6e64ee
!git clone --recursive --branch $branch https://github.com/pixray/pixray
!pip3 install -r ./reqs.txt
!pip install basicsr clip  timm==0.6.5 kornia==0.6.2 resmem
!pip uninstall -y tensorflow 
!git clone https://github.com/pixray/diffvg
%cd diffvg
!git submodule update --init --recursive
!python setup.py install
%cd ..
!pip freeze | grep torch

import sys
sys.path.append("pixray")
import pixray
```
good luck!
