### ISSUE TITLE
AttributeError: module 'timm.models' has no attribute 'registry'

### ISSUE THREAD

**Issue by TreeOfSelf** [pixray/pixray#95]
c:\Programming\pixray\pixray>python pixray.py --drawer=pixel --prompt=sunrise --outdir sunrise01
Traceback (most recent call last):
  File "c:\Programming\pixray\pixray\pixray.py", line 35, in <module>
    from slip import get_clip_perceptor
  File "c:\Programming\pixray\pixray\slip.py", line 80, in <module>
    import models
  File "C:\Programming\pixray\pixray\SLIP\models.py", line 257, in <module>
    @timm.models.registry.register_model
AttributeError: module 'timm.models' has no attribute 'registry'

**Comment by github-4o** [comment]
Having same issue on debian for command
`cog run python pixray.py --drawer=pixel --prompt=sunrise --outdir sunrise01top`

```
Running 'python pixray.py --drawer=pixel --prompt=sunrise --outdir sunrise01top' in Docker with the current directory mounted as a volume...
Traceback (most recent call last):
  File "pixray.py", line 35, in <module>
    from slip import get_clip_perceptor
  File "/src/slip.py", line 80, in <module>
    import models
  File "/src/SLIP/models.py", line 257, in <module>
    @timm.models.registry.register_model
AttributeError: module 'timm.models' has no attribute 'registry'
ⅹ exit status 1
```
